### ISSUE TITLE
Don't allow NA inside indices

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataArrays.jl#39]
As discussed in #38, any indexing operation that uses an NA index should fail. Right now, we simply drop NA's indices, but it's safer if you know that leaving NA's in your indices will always fail.

**Comment by matthieugomez** [comment]
For what it's worth, I'm in favor of returning errors whenever the indexing vector includes NA. I don't understand why someone would keep NA when indexing a row. I'm pretty sure that most of time this functionality is used, it is because of the user did not notice the indexing vector has an NA.
Besides, Panda and Stata does not allow NA in indexing (not sure about the rest).

An issue I can see with the flag option is that `skipna` means very different things in different contexts (as [skipping them when computing the mean](https://github.com/davidagold/NullableStats.jl/issues/1)).
